//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCabinetAvocat.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Affaire()
        {
            this.ProcedureJuridique = new HashSet<ProcedureJuridique>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Etat { get; set; }
        public int IdDossier { get; set; }
    
        public virtual Dossier Dossier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureJuridique> ProcedureJuridique { get; set; }
    }
}
