//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCabinetAvocat.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CabinetAvocatEntities : DbContext
    {
        public CabinetAvocatEntities()
            : base("name=CabinetAvocatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adherent> Adherent { get; set; }
        public virtual DbSet<Affaire> Affaire { get; set; }
        public virtual DbSet<Compte> Compte { get; set; }
        public virtual DbSet<Dossier> Dossier { get; set; }
        public virtual DbSet<Piece> Piece { get; set; }
        public virtual DbSet<ProcedureJuridique> ProcedureJuridique { get; set; }
        public virtual DbSet<RendezVous> RendezVous { get; set; }
    }
}
