//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCabinetAvocat.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendezVous
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string NomJuriste { get; set; }
        public System.DateTime DateRdv { get; set; }
        public Nullable<int> IdCompte { get; set; }
    
        public virtual Compte Compte { get; set; }
    }
}
